OREGON_HATCHERIES = [
    {"name": "Bonneville Hatchery", "river_system": "Columbia River", "region": "Columbia Gorge",
     "lat": 45.6440, "lon": -121.9349, "species": ["Chinook Salmon", "Coho Salmon", "Rainbow Trout"],
     "notes": "Largest in Oregon. Public tours available. Massive sturgeon pond on-site."},
    {"name": "Cascade Locks Hatchery", "river_system": "Columbia River", "region": "Columbia Gorge",
     "lat": 45.6710, "lon": -121.8988, "species": ["Coho Salmon", "Steelhead"],
     "notes": "State supplemental hatchery for Columbia Gorge salmon and steelhead."},
    {"name": "Oxbow Hatchery", "river_system": "Sandy River", "region": "Mt. Hood / Sandy",
     "lat": 45.4831, "lon": -122.2178, "species": ["Chinook Salmon", "Winter Steelhead", "Coho Salmon"],
     "notes": "Supports Sandy River runs. Public access at Oxbow Regional Park."},
    {"name": "Leaburg Hatchery", "river_system": "McKenzie River", "region": "Willamette Valley",
     "lat": 44.0941, "lon": -122.6624, "species": ["Spring Chinook", "Summer Steelhead", "Rainbow Trout"],
     "notes": "Major McKenzie River supplementation. H-clips on hatchery fish."},
    {"name": "McKenzie Hatchery", "river_system": "McKenzie River", "region": "Willamette Valley",
     "lat": 44.1560, "lon": -122.4834, "species": ["Coho Salmon", "Rainbow Trout"],
     "notes": "Coho supplementation for McKenzie system."},
    {"name": "Wizard Falls Hatchery", "river_system": "Metolius River", "region": "Central Oregon",
     "lat": 44.5236, "lon": -121.6497, "species": ["Atlantic Salmon", "Rainbow Trout", "Brown Trout", "Bull Trout"],
     "notes": "Unique — raises Atlantic salmon for catch & release. Excellent public viewing ponds. Must-visit."},
    {"name": "Round Butte Hatchery", "river_system": "Deschutes River", "region": "Central Oregon",
     "lat": 44.5382, "lon": -121.5029, "species": ["Spring Chinook", "Summer Steelhead", "Rainbow Trout"],
     "notes": "Below Pelton/Round Butte dams. Supports Middle Deschutes hatchery program."},
    {"name": "North Santiam Hatchery", "river_system": "North Santiam River", "region": "Willamette Valley",
     "lat": 44.7604, "lon": -122.4996, "species": ["Spring Chinook", "Winter Steelhead", "Rainbow Trout"],
     "notes": "Major Santiam supplementation program. Above Detroit Reservoir."},
    {"name": "South Santiam Hatchery", "river_system": "South Santiam River", "region": "Willamette Valley",
     "lat": 44.4720, "lon": -122.7910, "species": ["Spring Chinook", "Winter Steelhead"],
     "notes": "South Santiam supplementation. Below Foster Dam."},
    {"name": "Alsea Hatchery", "river_system": "Alsea River", "region": "Oregon Coast",
     "lat": 44.4071, "lon": -123.6068, "species": ["Coho Salmon", "Winter Steelhead", "Cutthroat Trout"],
     "notes": "One of the oldest ODFW hatcheries. Supports Alsea River fishery."},
    {"name": "Siletz Hatchery", "river_system": "Siletz River", "region": "Oregon Coast",
     "lat": 44.8975, "lon": -123.9257, "species": ["Winter Steelhead", "Coho Salmon"],
     "notes": "Siletz River supplementation. Near Lincoln City."},
    {"name": "Salmon River Hatchery", "river_system": "Salmon River", "region": "Oregon Coast",
     "lat": 45.0295, "lon": -123.9389, "species": ["Coho Salmon", "Winter Steelhead"],
     "notes": "Supports Lincoln County coastal rivers."},
    {"name": "Nehalem Hatchery", "river_system": "Nehalem River", "region": "Oregon Coast",
     "lat": 45.7023, "lon": -123.5671, "species": ["Coho Salmon", "Winter Steelhead", "Chinook Salmon"],
     "notes": "North coast salmon and steelhead supplementation."},
    {"name": "Trask River Hatchery", "river_system": "Trask River", "region": "Oregon Coast",
     "lat": 45.5093, "lon": -123.5019, "species": ["Winter Steelhead", "Spring Chinook", "Coho Salmon"],
     "notes": "Major Tillamook basin supplementation. Trask River access."},
    {"name": "Klaskanine Hatchery", "river_system": "Klaskanine River", "region": "Oregon Coast",
     "lat": 46.0482, "lon": -123.6826, "species": ["Coho Salmon", "Chinook Salmon"],
     "notes": "Lower Columbia coast. Near Astoria."},
    {"name": "Cole Rivers Hatchery", "river_system": "Rogue River", "region": "Southern Oregon",
     "lat": 42.5196, "lon": -122.7099, "species": ["Spring Chinook", "Coho Salmon", "Summer Steelhead", "Rainbow Trout"],
     "notes": "Largest Rogue Basin hatchery. Below Lost Creek Dam. Excellent public access."},
    {"name": "Applegate Hatchery", "river_system": "Applegate River", "region": "Southern Oregon",
     "lat": 42.0792, "lon": -123.1108, "species": ["Spring Chinook", "Rainbow Trout"],
     "notes": "Below Applegate Dam. Small facility."},
    {"name": "Elk River Hatchery", "river_system": "Elk River", "region": "Southern Oregon Coast",
     "lat": 42.7620, "lon": -124.3110, "species": ["Spring Chinook", "Winter Steelhead"],
     "notes": "South coast spring Chinook and steelhead supplementation."},
    {"name": "Chetco Hatchery", "river_system": "Chetco River", "region": "Southern Oregon Coast",
     "lat": 42.0548, "lon": -124.1831, "species": ["Winter Steelhead", "Spring Chinook", "Coho Salmon"],
     "notes": "Near Brookings. South coast program."},
    {"name": "Bandon Hatchery", "river_system": "Coquille River", "region": "Southern Oregon Coast",
     "lat": 43.1188, "lon": -124.3521, "species": ["Coho Salmon", "Winter Steelhead"],
     "notes": "Coquille River system supplementation."},
    {"name": "North Umpqua Hatchery", "river_system": "North Umpqua River", "region": "Southern Oregon",
     "lat": 43.2760, "lon": -123.0620, "species": ["Summer Steelhead", "Winter Steelhead", "Spring Chinook"],
     "notes": "North Umpqua supplementation. Downstream of fly-only section."},
    {"name": "Rock Creek Hatchery", "river_system": "Rock Creek / Umpqua", "region": "Southern Oregon",
     "lat": 43.5310, "lon": -123.6740, "species": ["Winter Steelhead", "Coho Salmon"],
     "notes": "Supports lower Umpqua coastal system."},
    {"name": "Irrigon Hatchery", "river_system": "Columbia River / Umatilla", "region": "Eastern Oregon",
     "lat": 45.8913, "lon": -119.4937, "species": ["Spring Chinook", "Fall Chinook", "Coho Salmon", "Steelhead"],
     "notes": "Major Lower Columbia/Umatilla supplementation. Tribal hatchery collaboration."},
    {"name": "Lookingglass Hatchery", "river_system": "Grande Ronde River", "region": "Eastern Oregon",
     "lat": 45.5027, "lon": -117.9033, "species": ["Spring Chinook", "Summer Steelhead"],
     "notes": "Grande Ronde/Snake supplementation. Nez Perce tribal collaboration."},
    {"name": "Joseph Hatchery", "river_system": "Wallowa River / Grande Ronde", "region": "Eastern Oregon",
     "lat": 45.3529, "lon": -117.2290, "species": ["Summer Steelhead", "Spring Chinook"],
     "notes": "Wallowa County. Supports upper Grande Ronde drainage."},
    {"name": "Roaring River Hatchery", "river_system": "Roaring River / North Santiam", "region": "Willamette Valley",
     "lat": 44.8490, "lon": -122.3560, "species": ["Rainbow Trout", "Brown Trout"],
     "notes": "Trophy trout program. Raises large fish for special regulations areas."},
    {"name": "Willamette Falls Hatchery", "river_system": "Willamette River", "region": "Willamette Valley",
     "lat": 45.3521, "lon": -122.6176, "species": ["Spring Chinook", "Winter Steelhead"],
     "notes": "Oregon City area. Spring Chinook return visible at Willamette Falls."},
    {"name": "Eagle Creek Hatchery", "river_system": "Clackamas River", "region": "Mt. Hood / Sandy",
     "lat": 45.3798, "lon": -122.3738, "species": ["Spring Chinook", "Winter Steelhead", "Coho Salmon"],
     "notes": "Major Clackamas supplementation. Chinook returns visible in fall."},
    {"name": "Klamath Hatchery", "river_system": "Klamath River", "region": "Southern Oregon",
     "lat": 42.2071, "lon": -121.7738, "species": ["Rainbow Trout", "Coho Salmon", "Steelhead"],
     "notes": "Upper Klamath basin. Post-dam-removal restoration context important."},
    {"name": "Fall Creek Hatchery", "river_system": "Fall Creek / Coast Fork Willamette", "region": "Willamette Valley",
     "lat": 43.9290, "lon": -122.7530, "species": ["Rainbow Trout", "Spring Chinook"],
     "notes": "Below Fall Creek Dam. Lane County fishery support."},
    {"name": "Summer Lake Hatchery", "river_system": "Summer Lake", "region": "Eastern Oregon",
     "lat": 42.9776, "lon": -120.7730, "species": ["Rainbow Trout"],
     "notes": "High desert trout production for Eastern Oregon stocking."},
]

OREGON_LAKES = [
    {"name": "Lake Billy Chinook", "region": "Central Oregon", "lat": 44.5390, "lon": -121.4960,
     "species": ["Kokanee", "Bull Trout", "Smallmouth Bass", "Redband Rainbow"],
     "regulations": "Standard Oregon regs. Boat required for most access.",
     "notes": "Reservoir behind Round Butte Dam. Excellent kokanee in June–August. Trolling preferred."},
    {"name": "Wickiup Reservoir", "region": "Central Oregon", "lat": 43.6850, "lon": -121.7260,
     "species": ["Brown Trout", "Rainbow Trout", "Kokanee", "White Crappie"],
     "regulations": "Fly-fishing only on designated areas. Big browns to 10+ lbs.",
     "notes": "One of Oregon's best trophy brown trout fisheries. Ice fishing December–February."},
    {"name": "Crane Prairie Reservoir", "region": "Central Oregon", "lat": 43.7890, "lon": -121.8080,
     "species": ["Largemouth Bass", "Rainbow Trout", "Brown Trout", "Crappie"],
     "regulations": "Mix of fly-fishing and general regs depending on area.",
     "notes": "Outstanding bass water. Weed beds provide great structure. Float tube access excellent."},
    {"name": "Davis Lake", "region": "Central Oregon", "lat": 43.5830, "lon": -121.8360,
     "species": ["Rainbow Trout"],
     "regulations": "Fly-fishing only, artificial lures only. Large rainbows to 5+ lbs.",
     "notes": "Trophy fly-only lake. Leech and damsel fly patterns. Best May–June and September."},
    {"name": "Odell Lake", "region": "Central Oregon", "lat": 43.5560, "lon": -121.8520,
     "species": ["Lake Trout (Mackinaw)", "Kokanee", "Rainbow Trout", "Bull Trout"],
     "regulations": "Standard Oregon regs. Deep trolling for lake trout.",
     "notes": "One of Oregon's best kokanee lakes. Mac lake to 30+ lbs possible. Access via Hwy 58."},
    {"name": "Waldo Lake", "region": "Willamette Valley / Cascades", "lat": 43.7420, "lon": -122.0210,
     "species": ["Rainbow Trout", "Brook Trout"],
     "regulations": "Fly-fishing and artificial lures only. No motors (electric only).",
     "notes": "One of the purest lakes in the world. Small but wild trout. Wilderness hiking required."},
    {"name": "Detroit Reservoir", "region": "Willamette Valley", "lat": 44.7230, "lon": -122.2500,
     "species": ["Kokanee", "Rainbow Trout", "Brown Trout"],
     "regulations": "Standard Oregon regs.",
     "notes": "North Santiam impoundment. Excellent kokanee mid-summer. Boat launch at Mongold State Park."},
    {"name": "Timothy Lake", "region": "Mt. Hood / Sandy", "lat": 45.1150, "lon": -121.7870,
     "species": ["Rainbow Trout", "Kokanee", "Cutthroat Trout"],
     "regulations": "Standard Oregon regs.",
     "notes": "Mt. Hood National Forest. Good kokanee and rainbow. Campground access."},
    {"name": "Lost Lake", "region": "Mt. Hood / Sandy", "lat": 45.4950, "lon": -121.8210,
     "species": ["Rainbow Trout", "Brook Trout"],
     "regulations": "Standard Oregon regs. Boat rentals available.",
     "notes": "Classic Mt. Hood lake. Stocked regularly. Kayak/canoe fishing productive."},
    {"name": "Henry Hagg Lake", "region": "Willamette Valley", "lat": 45.4760, "lon": -123.2260,
     "species": ["Rainbow Trout", "Largemouth Bass", "Smallmouth Bass", "Crappie"],
     "regulations": "Standard Oregon regs.",
     "notes": "Washington County reservoir. Year-round trout stocking. Good bass April–October."},
    {"name": "Fern Ridge Reservoir", "region": "Willamette Valley", "lat": 44.1210, "lon": -123.3050,
     "species": ["Largemouth Bass", "Crappie", "Catfish", "Yellow Perch"],
     "regulations": "Standard Oregon regs.",
     "notes": "Lane County. Best bass in the valley. Catfish stocking in summer."},
    {"name": "Wallowa Lake", "region": "Eastern Oregon", "lat": 45.2720, "lon": -117.2080,
     "species": ["Kokanee", "Bull Trout", "Rainbow Trout"],
     "regulations": "Catch & release for bull trout. Standard regs otherwise.",
     "notes": "Spectacular Wallowa Mountains setting. Kokanee in July–September. State park access."},
    {"name": "Howard Prairie Reservoir", "region": "Southern Oregon", "lat": 42.2180, "lon": -122.4580,
     "species": ["Rainbow Trout", "Brown Trout", "Largemouth Bass"],
     "regulations": "Standard Oregon regs.",
     "notes": "Jackson County. Spring and fall trout best. Good bass mid-summer."},
    {"name": "Hyatt Reservoir", "region": "Southern Oregon", "lat": 42.1530, "lon": -122.4190,
     "species": ["Rainbow Trout", "Brown Trout"],
     "regulations": "Standard Oregon regs.",
     "notes": "High Cascade reservoir near Medford. Trolling and fly fishing productive."},
    {"name": "Ana Reservoir", "region": "Eastern Oregon", "lat": 42.6220, "lon": -120.6810,
     "species": ["Rainbow Trout"],
     "regulations": "Fly-fishing and artificial lures only. Trophy class fish.",
     "notes": "Spring-fed reservoir near Summer Lake. Large rainbows. Remote but productive."},
    {"name": "Applegate Reservoir", "region": "Southern Oregon", "lat": 42.0540, "lon": -123.1030,
     "species": ["Rainbow Trout", "Largemouth Bass", "Smallmouth Bass"],
     "regulations": "Standard Oregon regs.",
     "notes": "Jackson County. Spring trout; bass summer through fall."},
    {"name": "Blue Lake (Columbia Gorge)", "region": "Columbia Gorge", "lat": 45.5990, "lon": -122.4040,
     "species": ["Rainbow Trout"],
     "regulations": "Standard Oregon regs.",
     "notes": "Metro area lake. Heavily stocked. Family-friendly access."},
    {"name": "Thief Valley Reservoir", "region": "Eastern Oregon", "lat": 44.9590, "lon": -117.6320,
     "species": ["Rainbow Trout", "Smallmouth Bass", "Crappie"],
     "regulations": "Standard Oregon regs.",
     "notes": "Baker County. Good bass and trout combo fishery."},
    {"name": "Prineville Reservoir", "region": "Central Oregon", "lat": 44.2700, "lon": -120.7490,
     "species": ["Rainbow Trout", "Largemouth Bass", "Smallmouth Bass", "Crappie"],
     "regulations": "Standard Oregon regs.",
     "notes": "Crooked River impoundment. Trophy bass. Crappie in spring. Boat recommended."},
    {"name": "Lostine / Wallowa River Ponds", "region": "Eastern Oregon", "lat": 45.4940, "lon": -117.4300,
     "species": ["Rainbow Trout", "Brook Trout"],
     "regulations": "Standard Oregon regs.",
     "notes": "Small alpine ponds near Wallowa Lake. Walk-in access. Wild fish."},
]
